{
 'FBI': 'Federal Bureau of Investigation',
 'DOJ': 'Department of Justice',
 'MSM': 'Mainstream Media',
 'EU': 'European Union',
 'Anon': 'Anonymous',
 'POTUS': 'President of the United States',
 'WW': 'World War, World Wide',
 'SAT': 'Satellite',
 'SC': 'Supreme Court, Special Counsel',
 'FISA': 'Foreign Intelligence Surveillance Act',
 'RR': 'Rod Rosenstein',
 'AF1': 'Air Force One',
 'EO': 'Executive Order',
 'USSS': 'United States Secret Service',
 'LARP': 'Live Action Role Play',
 'U1': 'Uranium 1',
 'DC': 'District of Columbia',
 'CF': 'Clinton Foundation',
 'SEC': 'Security or Secure',
 'UK': 'United Kingdom',
 'AUS': 'Australia',
 'WL': 'Wikileaks',
 'WH': 'White House',
 'PS': 'Peter Strzok',
 'CA': 'California',
 'FED': 'Federal Reserve',
 'ID': 'Identification',
 'AG': 'Attorney General',
 'ANTIFA': 'Anti-Fascists, Soros backed domestic terrorists',
 "D's": 'Democrats',
 'FF': 'False Flag Attack',
 'MS13': 'Latino International Criminal Gang',
 'ISIS': 'Islamic State of Iraq and Syria, Israeli Secret Intelligence Service',
 'FOIA': 'Freedom of Information Act',
 'NSA': 'National Security Agency',
 'OP': 'Original Poster or Operation',
 'HRC': 'Hillary Rodham Clinton',
 'GOOG': 'Google',
 'IG': 'Inspector General, Instagram',
 'LL': 'Loretta Lynch',
 'CIA': 'Central Intelligence Agency',
 'JC': 'James Comey, James Clapper',
 'C_A': '(CIA) Central Intelligence Agency',
 'FB': 'Facebook',
 'MO': 'Michelle Obama',
 'BO': 'Barack Obama or Board Owner',
 'BC': 'Bill Clinton',
 'FVEY': 'Five Eyes',
 'CM': 'CodeMonkey, 8chan Administrator',
 '187': 'Murder',
 'MOAB': 'Mother of All Bombs (Booms)',
 'AJ': 'Alex Jones',
 'SA': 'Saudi Arabia',
 'AS': 'Adam Schiff',
 'MOS': 'Mossad',
 '@Jack': 'Jack Dorsey',
 'NP': 'Non-Profit, Nancy Pelosi',
 'ES': 'Eric Schmidt',
 'SS': 'Secret Service',
 'MH': 'Melissa Hodgman',
 '@Snowden': 'Edward Snowden',
 'CS': 'Chuck Schumer, CrowdStrike',
 'MIL': 'Military',
 'JB': 'John Owen Brennan',
 'VJ': 'Valerie Jarrett',
 'NK': 'North Korea',
 'ICE': 'United States Immigration and Customs Enforcement',
 'NG': 'National Guard',
 'JK': 'John Kerry, Jared Kushner',
 'DNC': 'Democratic National Committee',
 'MM': 'Media Matters',
 'AM': 'Andrew McCabe',
 'BP': 'Border Patrol',
 'LP': 'Lisa Page',
 'TG': 'Trey Gowdy',
 'HA': 'Huma Mahmood Abedin',
 'JP': 'John Podesta',
 'PM': 'Prime Minister',
 'JA': 'Julian Assange',
 'MA': 'Michael Avenatti',
 'BOD': 'Board of Directors',
 'DEFCON': 'DEFense readiness CONdition',
 'MZ': 'Mark Zuckerburg',
 'SR': 'Susan Rice or Seth Rich',
 'MS-13': 'Latino International Criminal Gang',
 'EH': 'Eric Holder',
 'JFK': 'John Fitzgereld Kennedy',
 'MB': 'Muslim Brotherhood',
 'Adm R': 'Admiral Michael Rogers',
 'JL': 'John Legend',
 'GZ': 'Ground Zero',
 'GS': 'George Soros',
 'HUMA': 'Harvard University Muslim Alumni',
 'CHAI': 'Clinton Health Access Initiative',
 'BDT': 'Bangladeshi Taka, ref. Bangladesh',
 'RT': 'Rex Tillerson, Rizvi Traverse, Real Time, ReTweet',
 'EITS': 'Enterprise Information Technology Services',
 'GWB': 'George W. Bush',
 'RC': 'Rachel Chandler',
 'PG': 'PizzaGate / PedoGate',
 'NWO': 'New World Order',
 'LdR': 'Lynn Forester de Rothschild',
 'IBOR': 'Internet Bill of Rights',
 'SAP': 'Special Access Programs',
 'TP': 'Tony Podesta',
 'US-G': 'United States Government',
 'LV': 'Las Vegas',
 'MI': 'Military Intelligence',
 'EMS': 'Emergency Medical Services',
 'SOTU': 'State of the Union',
 'MW': 'Maxine Waters',
 'HW': 'Hollywood',
 'PSYOP': 'Psychological Operation',
 'JS': 'John Solomon',
 'EM': 'Elon Musk',
 'SH': 'Steve Huffman',
 'IRS': 'Internal Revenue Agency',
 'HEC': 'United States House Committee on Ethics',
 'F-I': 'Federal Bureau of Investigation',
 'D-J': 'Department of Justice', 
 'C-A': 'Central Intelligence Agency', 
 'H-wood': 'Hollywood', 
 'ST': 'Seal Team (eg. Seal Team 6)',
 'ML': 'Marshal Law', 
 'KKK': 'Ku Klux Klan', 
 'HS': 'Homeland Security',
 'HI': 'Hawaii',
 'C19': 'covid',
 "R's": 'Republicans',
 "US M's": 'US Marshalls'}